"use client";

import { useEffect, useState } from "react";

const projects = [["SpaceForge", "Interactive game", "SF", "space"], ["Gozuos", "Travel platform", "G", "gozuos"], ["Chatiom", "Social intelligence", "C", "chat"], ["IVR System", "Voice operations", "IVR", "ivr"], ["Windows Apps", "Desktop tools", "W", "windows"]];
const technologies = ["React", "Next.js", "Node.js", "TypeScript", "Python", "AWS", "Docker", "Postgres", "MongoDB", "Redis", "Tailwind", "Figma"];
const copy = {
  en: { nav: ["Home", "Projects", "Technologies", "About Us", "Careers"], kicker: "Digital products, engineered differently", hero: "Building next-gen solutions for a", accent: "smarter tomorrow.", intro: "We turn ambitious ideas into powerful, human-centered digital experiences that move businesses and people forward.", explore: "Explore our work", learn: "Learn more", trusted: "Trusted by innovators worldwide", projects: "Our projects", projectTitle: "Innovative products.", projectAccent: "Real impact.", all: "View all projects", stack: "Technology stack", stackTitle: "Powered by modern", stackAccent: "technologies.", stackIntro: "The right tools make ambitious ideas possible. We use a considered stack built for speed, scale, and staying power.", why: "Why choose Questdrium?", whyTitle: "We turn ideas into", whyAccent: "powerful digital solutions.", whyText: "From the first sketch to the final launch, we bring clarity, craft, and curiosity to every build.", about: "About us", idea: "Have a bold idea?", cta: "Ready to build something", ctaAccent: "amazing together?", contact: "Get in touch", made: "Made for what’s next" },
  es: { nav: ["Inicio", "Proyectos", "Tecnologías", "Nosotros", "Carreras"], kicker: "Productos digitales, diseñados diferente", hero: "Construimos soluciones de próxima generación para un", accent: "mañana más inteligente.", intro: "Convertimos ideas ambiciosas en experiencias digitales humanas y potentes que hacen avanzar a las empresas y las personas.", explore: "Explora nuestro trabajo", learn: "Conoce más", trusted: "La confianza de innovadores de todo el mundo", projects: "Nuestros proyectos", projectTitle: "Productos innovadores.", projectAccent: "Impacto real.", all: "Ver todos los proyectos", stack: "Tecnologías", stackTitle: "Impulsados por", stackAccent: "tecnologías modernas.", stackIntro: "Las herramientas correctas hacen posibles las grandes ideas. Usamos una base pensada para velocidad, escala y permanencia.", why: "¿Por qué Questdrium?", whyTitle: "Convertimos ideas en", whyAccent: "soluciones digitales potentes.", whyText: "Desde el primer boceto hasta el lanzamiento, aportamos claridad, oficio y curiosidad a cada proyecto.", about: "Conócenos", idea: "¿Tienes una gran idea?", cta: "¿Listo para construir algo", ctaAccent: "increíble juntos?", contact: "Contáctanos", made: "Hecho para lo que sigue" },
};
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  const [language, setLanguage] = useState<"en" | "es">("en");
  const [menuOpen, setMenuOpen] = useState(false);
  const text = copy[language];
  const links = ["home", "projects", "technologies", "about", "contact"];
  useEffect(() => { document.body.style.overflow = menuOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen]);
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="brand" href="#home" onClick={() => setMenuOpen(false)}><span className="brand-mark">Q</span><span><strong>Questdrium</strong><small>NEXT-GEN TECHNOLOGIES</small></span></a><div className={`nav-links ${menuOpen ? "mobile-open" : ""}`}>{text.nav.map((item, index) => <a key={item} href={`#${links[index]}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a className="mobile-admin-link" href="/master" onClick={() => setMenuOpen(false)}>Master login ↗</a></div><div className="nav-tools"><button className="language" onClick={() => setLanguage(language === "en" ? "es" : "en")} aria-label="Switch language">{language === "en" ? "ES" : "EN"}</button><a className="button button-small button-gradient" href="#contact">{language === "en" ? "Contact us" : "Contáctanos"} <Arrow /></a></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? "Close navigation" : "Open navigation"}>{menuOpen ? "×" : "☰"}</button></nav>
    <section className="hero shell" id="home"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> {text.kicker}</p><h1>{text.hero} <em>{text.accent}</em></h1><p className="hero-description">{text.intro}</p><div className="hero-actions"><a className="button button-gradient" href="#projects">{text.explore} <Arrow /></a><a className="button button-outline" href="#about">{text.learn} <span>↓</span></a></div></div><div className="hero-art"><div className="art-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="q-core">Q</div><div className="core-glow" /><div className="art-caption"><span>QUESTDRIUM / 01</span><strong>Signal in the noise</strong></div></div><div className="proof"><span>{text.trusted}</span><div><b>AWS</b><b>twilio</b><b>stripe</b><b>◉ React</b><b>node</b></div></div></section>
    <section className="section shell" id="projects"><div className="section-heading"><div><p className="eyebrow">{text.projects}</p><h2>{text.projectTitle}<br /><em>{text.projectAccent}</em></h2></div><a className="text-link" href="#contact">{text.all} <Arrow /></a></div><div className="project-grid">{projects.map(([name, type, mark, visual], index) => <article className="project-card" key={name}><div className={`project-visual ${visual}`}><span className="project-mark">{mark}</span><span className={`status ${index === 2 ? "beta" : ""}`}>{index === 2 ? "BETA" : "LIVE"}</span><div className="visual-lines" /></div><div className="project-info"><div><h3>{name}</h3><p>{type}</p></div><span className="card-arrow">↗</span></div></article>)}</div><div className="pagination"><span className="active" /><span /><span /><span /></div></section>
    <section className="stack-section" id="technologies"><div className="shell centered"><p className="eyebrow pink">{text.stack}</p><h2>{text.stackTitle} <em>{text.stackAccent}</em></h2><p className="section-intro">{text.stackIntro}</p><div className="tech-grid">{technologies.map((technology, index) => <div className="tech-tile" key={technology}><span className={`tech-icon icon-${index}`}>{technology === "TypeScript" ? "TS" : technology.slice(0, 2)}</span><span>{technology}</span></div>)}</div></div></section>
    <section className="section about-section shell" id="about"><div className="about-copy"><p className="eyebrow">{text.why}</p><h2>{text.whyTitle} <em>{text.whyAccent}</em></h2><p>{text.whyText}</p><a className="button button-gradient" href="#contact">{text.about} <Arrow /></a></div><div className="stats-grid"><div><span>↗</span><strong>20+</strong><p>Projects delivered</p></div><div><span>◎</span><strong>10K+</strong><p>Active users</p></div><div><span>◌</span><strong>99.9%</strong><p>Uptime shipped</p></div><div><span>♡</span><strong>5+</strong><p>Years of innovation</p></div></div></section>
    <section className="cta shell" id="contact"><div className="cta-wave" /><div><p className="eyebrow pink">{text.idea}</p><h2>{text.cta}<br /><em>{text.ctaAccent}</em></h2></div><a className="button button-gradient" href="mailto:hello@questdrium.tech">{text.contact} <Arrow /></a></section>
    <footer className="footer shell"><div className="footer-top"><div className="footer-brand"><a className="brand" href="#home"><span className="brand-mark">Q</span><span><strong>Questdrium</strong><small>NEXT-GEN TECHNOLOGIES</small></span></a><p>Digital products for a<br />smarter tomorrow.</p></div><div className="footer-links"><div><b>Company</b><a href="#about">About us</a><a href="#contact">Careers</a><a href="#contact">Contact</a></div><div><b>Services</b><a href="#contact">Product design</a><a href="#contact">Development</a><a href="#contact">Strategy</a></div><div className="social-links"><b>Connect</b><a href="#contact" aria-label="LinkedIn">in</a><a href="#contact" aria-label="GitHub">◖</a><a href="#contact" aria-label="Twitter" className="twitter-icon">♥</a><a href="/master" aria-label="Master login">⌘</a></div></div></div><div className="footer-bottom"><span>© 2026 Questdrium Technologies. All rights reserved.</span><span>{text.made} <b>✦</b></span></div></footer>
  </main>;
}
